export const dataBase = {
    winners: [
      {
        id: 1,
        name: 'achristaeas0',
        score: 3,
        state: 'alive',
        totalKills: 37,
        deaths: 6,
      },
      {
        id: 2,
        name: 'bhelliwell1',
        score: 4,
        state: 'alive',
        totalKills: 20,
        deaths: 31,
      },
      {
        id: 3,
        name: 'smccarlie2',
        score: 0,
        state: 'dead',
        totalKills: 28,
        deaths: 31,
      },
      {
        id: 4,
        name: 'ebattlestone3',
        score: 1,
        state: 'alive',
        totalKills: 39,
        deaths: 22,
      },
      {
        id: 5,
        name: 'rglusby4',
        score: 0,
        state: 'alive',
        totalKills: 31,
        deaths: 20,
      },
      {
        id: 6,
        name: 'zstanfield5',
        score: 3,
        state: 'dead',
        totalKills: 39,
        deaths: 0,
      },
      {
        id: 7,
        name: 'vfarrin6',
        score: 0,
        state: 'dead',
        totalKills: 40,
        deaths: 19,
      },
      {
        id: 8,
        name: 'mfetter7',
        score: 3,
        state: 'dead',
        totalKills: 1,
        deaths: 39,
      },
      {
        id: 9,
        name: 'touterbridge8',
        score: 0,
        state: 'dead',
        totalKills: 29,
        deaths: 46,
      },
      {
        id: 10,
        name: 'emockes9',
        score: 0,
        state: 'alive',
        totalKills: 38,
        deaths: 44,
      },
      {
        id: 11,
        name: 'wvadera',
        score: 5,
        state: 'alive',
        totalKills: 34,
        deaths: 41,
      },
      {
        id: 12,
        name: 'hwrassellb',
        score: 2,
        state: 'dead',
        totalKills: 34,
        deaths: 38,
      },
      {
        id: 13,
        name: 'ktomasianc',
        score: 5,
        state: 'dead',
        totalKills: 22,
        deaths: 39,
      },
      {
        id: 14,
        name: 'araed',
        score: 4,
        state: 'alive',
        totalKills: 37,
        deaths: 43,
      },
      {
        id: 15,
        name: 'vgartlande',
        score: 4,
        state: 'alive',
        totalKills: 35,
        deaths: 42,
      },
      {
        id: 16,
        name: 'nduxfieldf',
        score: 1,
        state: 'dead',
        totalKills: 16,
        deaths: 35,
      },
      {
        id: 17,
        name: 'zbenesg',
        score: 5,
        state: 'dead',
        totalKills: 22,
        deaths: 10,
      },
      {
        id: 18,
        name: 'hberringtonh',
        score: 1,
        state: 'alive',
        totalKills: 31,
        deaths: 6,
      },
      {
        id: 19,
        name: 'agoldhawki',
        score: 0,
        state: 'alive',
        totalKills: 40,
        deaths: 34,
      },
      {
        id: 20,
        name: 'gcoultousj',
        score: 2,
        state: 'dead',
        totalKills: 5,
        deaths: 23,
      },
      {
        id: 21,
        name: 'vhollyerk',
        score: 4,
        state: 'dead',
        totalKills: 39,
        deaths: 28,
      },
      {
        id: 22,
        name: 'hmapplethorpel',
        score: 1,
        state: 'alive',
        totalKills: 41,
        deaths: 18,
      },
      {
        id: 23,
        name: 'yvonderdellm',
        score: 5,
        state: 'alive',
        totalKills: 11,
        deaths: 3,
      },
      {
        id: 24,
        name: 'tteddern',
        score: 0,
        state: 'alive',
        totalKills: 31,
        deaths: 3,
      },
      {
        id: 25,
        name: 'vskarmano',
        score: 3,
        state: 'alive',
        totalKills: 18,
        deaths: 49,
      },
      {
        id: 26,
        name: 'acaldarop',
        score: 4,
        state: 'dead',
        totalKills: 37,
        deaths: 46,
      },
      {
        id: 27,
        name: 'omctrustyq',
        score: 1,
        state: 'alive',
        totalKills: 9,
        deaths: 13,
      },
      {
        id: 28,
        name: 'dbevansr',
        score: 4,
        state: 'alive',
        totalKills: 47,
        deaths: 33,
      },
      {
        id: 29,
        name: 'ddebischofs',
        score: 2,
        state: 'dead',
        totalKills: 7,
        deaths: 23,
      },
      {
        id: 30,
        name: 'arobothamt',
        score: 2,
        state: 'dead',
        totalKills: 11,
        deaths: 8,
      },
      {
        id: 31,
        name: 'eausticku',
        score: 1,
        state: 'dead',
        totalKills: 12,
        deaths: 11,
      },
      {
        id: 32,
        name: 'ctennetv',
        score: 4,
        state: 'dead',
        totalKills: 27,
        deaths: 19,
      },
      {
        id: 33,
        name: 'rmargueritew',
        score: 3,
        state: 'dead',
        totalKills: 49,
        deaths: 39,
      },
      {
        id: 34,
        name: 'squinseex',
        score: 4,
        state: 'dead',
        totalKills: 13,
        deaths: 31,
      },
      {
        id: 35,
        name: 'wprotheroy',
        score: 5,
        state: 'dead',
        totalKills: 40,
        deaths: 17,
      },
      {
        id: 36,
        name: 'ndoreez',
        score: 4,
        state: 'dead',
        totalKills: 9,
        deaths: 34,
      },
      {
        id: 37,
        name: 'mnaylor10',
        score: 4,
        state: 'alive',
        totalKills: 0,
        deaths: 47,
      },
      {
        id: 38,
        name: 'wjurczik11',
        score: 3,
        state: 'alive',
        totalKills: 22,
        deaths: 25,
      },
      {
        id: 39,
        name: 'ecoldbathe12',
        score: 5,
        state: 'dead',
        totalKills: 10,
        deaths: 35,
      },
      {
        id: 40,
        name: 'mpatington13',
        score: 5,
        state: 'dead',
        totalKills: 25,
        deaths: 1,
      },
      {
        id: 41,
        name: 'afireman14',
        score: 1,
        state: 'dead',
        totalKills: 47,
        deaths: 15,
      },
      {
        id: 42,
        name: 'sscraggs15',
        score: 3,
        state: 'alive',
        totalKills: 1,
        deaths: 49,
      },
      {
        id: 43,
        name: 'tmunt16',
        score: 3,
        state: 'alive',
        totalKills: 49,
        deaths: 5,
      },
      {
        id: 44,
        name: 'lfernan17',
        score: 3,
        state: 'alive',
        totalKills: 19,
        deaths: 4,
      },
      {
        id: 45,
        name: 'mspittal18',
        score: 0,
        state: 'alive',
        totalKills: 39,
        deaths: 49,
      },
      {
        id: 46,
        name: 'vflannery19',
        score: 4,
        state: 'dead',
        totalKills: 48,
        deaths: 38,
      },
      {
        id: 47,
        name: 'achatenet1a',
        score: 1,
        state: 'alive',
        totalKills: 28,
        deaths: 9,
      },
      {
        id: 48,
        name: 'nmelmeth1b',
        score: 2,
        state: 'dead',
        totalKills: 40,
        deaths: 48,
      },
      {
        id: 49,
        name: 'lollander1c',
        score: 2,
        state: 'alive',
        totalKills: 23,
        deaths: 20,
      },
      {
        id: 50,
        name: 'pmaxwell1d',
        score: 5,
        state: 'alive',
        totalKills: 31,
        deaths: 21,
      },
    ],
    losers: [
      {
        id: 1,
        name: 'rbate0',
        score: 3,
        state: 'dead',
        totalKills: 25,
        deaths: 17,
      },
      {
        id: 2,
        name: 'fweiner1',
        score: 5,
        state: 'dead',
        totalKills: 10,
        deaths: 49,
      },
      {
        id: 3,
        name: 'bweeke2',
        score: 4,
        state: 'alive',
        totalKills: 17,
        deaths: 49,
      },
      {
        id: 4,
        name: 'kphillips3',
        score: 4,
        state: 'dead',
        totalKills: 18,
        deaths: 44,
      },
      {
        id: 5,
        name: 'edechastelain4',
        score: 3,
        state: 'alive',
        totalKills: 6,
        deaths: 41,
      },
      {
        id: 6,
        name: 'oblomefield5',
        score: 0,
        state: 'dead',
        totalKills: 21,
        deaths: 12,
      },
      {
        id: 7,
        name: 'lsheehan6',
        score: 0,
        state: 'dead',
        totalKills: 4,
        deaths: 41,
      },
      {
        id: 8,
        name: 'csoff7',
        score: 5,
        state: 'dead',
        totalKills: 40,
        deaths: 7,
      },
      {
        id: 9,
        name: 'cdishmon8',
        score: 5,
        state: 'alive',
        totalKills: 38,
        deaths: 15,
      },
      {
        id: 10,
        name: 'rsamet9',
        score: 2,
        state: 'alive',
        totalKills: 28,
        deaths: 47,
      },
      {
        id: 11,
        name: 'mhugonneaua',
        score: 0,
        state: 'alive',
        totalKills: 9,
        deaths: 28,
      },
      {
        id: 12,
        name: 'kparmeterb',
        score: 5,
        state: 'dead',
        totalKills: 16,
        deaths: 19,
      },
      {
        id: 13,
        name: 'rfrigoutc',
        score: 2,
        state: 'alive',
        totalKills: 19,
        deaths: 2,
      },
      {
        id: 14,
        name: 'jlarmouthd',
        score: 1,
        state: 'dead',
        totalKills: 47,
        deaths: 30,
      },
      {
        id: 15,
        name: 'mromanete',
        score: 0,
        state: 'alive',
        totalKills: 45,
        deaths: 20,
      },
      {
        id: 16,
        name: 'cphilsonf',
        score: 2,
        state: 'alive',
        totalKills: 3,
        deaths: 35,
      },
      {
        id: 17,
        name: 'fdeathg',
        score: 4,
        state: 'dead',
        totalKills: 45,
        deaths: 49,
      },
      {
        id: 18,
        name: 'jlyfieldh',
        score: 0,
        state: 'alive',
        totalKills: 44,
        deaths: 39,
      },
      {
        id: 19,
        name: 'sdealmeidai',
        score: 5,
        state: 'alive',
        totalKills: 21,
        deaths: 30,
      },
      {
        id: 20,
        name: 'mdeavallj',
        score: 5,
        state: 'alive',
        totalKills: 28,
        deaths: 30,
      },
      {
        id: 21,
        name: 'tkubatk',
        score: 5,
        state: 'alive',
        totalKills: 12,
        deaths: 16,
      },
      {
        id: 22,
        name: 'acoldhaml',
        score: 0,
        state: 'alive',
        totalKills: 30,
        deaths: 18,
      },
      {
        id: 23,
        name: 'cfachem',
        score: 3,
        state: 'alive',
        totalKills: 34,
        deaths: 13,
      },
      {
        id: 24,
        name: 'cbythwayn',
        score: 2,
        state: 'alive',
        totalKills: 44,
        deaths: 39,
      },
      {
        id: 25,
        name: 'nsizeo',
        score: 2,
        state: 'alive',
        totalKills: 29,
        deaths: 35,
      },
      {
        id: 26,
        name: 'rschulkinsp',
        score: 5,
        state: 'alive',
        totalKills: 27,
        deaths: 49,
      },
      {
        id: 27,
        name: 'erontschq',
        score: 1,
        state: 'alive',
        totalKills: 9,
        deaths: 42,
      },
      {
        id: 28,
        name: 'ahuonicr',
        score: 5,
        state: 'dead',
        totalKills: 32,
        deaths: 1,
      },
      {
        id: 29,
        name: 'tgillcrists',
        score: 5,
        state: 'alive',
        totalKills: 39,
        deaths: 30,
      },
      {
        id: 30,
        name: 'wespinosat',
        score: 5,
        state: 'alive',
        totalKills: 4,
        deaths: 12,
      },
      {
        id: 31,
        name: 'jmiddenu',
        score: 5,
        state: 'alive',
        totalKills: 33,
        deaths: 18,
      },
      {
        id: 32,
        name: 'cpignev',
        score: 0,
        state: 'dead',
        totalKills: 43,
        deaths: 36,
      },
      {
        id: 33,
        name: 'aritchmanw',
        score: 3,
        state: 'alive',
        totalKills: 44,
        deaths: 28,
      },
      {
        id: 34,
        name: 'amcfeatex',
        score: 2,
        state: 'alive',
        totalKills: 30,
        deaths: 8,
      },
      {
        id: 35,
        name: 'rfaradayy',
        score: 1,
        state: 'dead',
        totalKills: 28,
        deaths: 2,
      },
      {
        id: 36,
        name: 'fitzkovwichz',
        score: 2,
        state: 'dead',
        totalKills: 9,
        deaths: 13,
      },
      {
        id: 37,
        name: 'kgarrigan10',
        score: 1,
        state: 'dead',
        totalKills: 34,
        deaths: 9,
      },
      {
        id: 38,
        name: 'pguillard11',
        score: 0,
        state: 'alive',
        totalKills: 42,
        deaths: 22,
      },
      {
        id: 39,
        name: 'balastair12',
        score: 3,
        state: 'alive',
        totalKills: 27,
        deaths: 9,
      },
      {
        id: 40,
        name: 'bsandaver13',
        score: 1,
        state: 'dead',
        totalKills: 38,
        deaths: 42,
      },
      {
        id: 41,
        name: 'ppandey14',
        score: 4,
        state: 'alive',
        totalKills: 33,
        deaths: 45,
      },
      {
        id: 42,
        name: 'kgreensite15',
        score: 1,
        state: 'dead',
        totalKills: 15,
        deaths: 30,
      },
      {
        id: 43,
        name: 'smeeland16',
        score: 0,
        state: 'alive',
        totalKills: 6,
        deaths: 3,
      },
      {
        id: 44,
        name: 'cphilps17',
        score: 0,
        state: 'dead',
        totalKills: 42,
        deaths: 3,
      },
      {
        id: 45,
        name: 'apoulglais18',
        score: 2,
        state: 'alive',
        totalKills: 4,
        deaths: 37,
      },
      {
        id: 46,
        name: 'ksorensen19',
        score: 2,
        state: 'alive',
        totalKills: 20,
        deaths: 11,
      },
      {
        id: 47,
        name: 'tsomerscales1a',
        score: 5,
        state: 'dead',
        totalKills: 7,
        deaths: 37,
      },
      {
        id: 48,
        name: 'growden1b',
        score: 4,
        state: 'dead',
        totalKills: 35,
        deaths: 46,
      },
      {
        id: 49,
        name: 'kpiquard1c',
        score: 0,
        state: 'alive',
        totalKills: 28,
        deaths: 28,
      },
      {
        id: 50,
        name: 'rdidomenico1d',
        score: 0,
        state: 'dead',
        totalKills: 41,
        deaths: 26,
      },
    ]
  };